core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('kdr.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('stock.urls'))
]

kdr/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="kdr/home.html"), name="home")
]

stock/urls.py
from django.urls import path
from stock.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

urlpatterns = [
    path("", ProductListView.as_view(), name="product-list"),
    path("create/", ProductCreateView.as_view(), name="product-create"),
    path("<slug:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("<slug:pk>/update", ProductUpdateView.as_view(), name="product-update"),
    path("<slug:pk>/delete", ProductDeleteView.as_view(), name="product-delete")
]

kdr/models.py
from django.db import models

# Create your models here.

stock/models.py
from django.db import models

class Manufacturer(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return f'{self.name}'

class UnitType(models.Model):
    name = models.CharField(max_length=128)
    symbol = models.CharField(max_length=32)

    def __str__(self):
        return f'{self.symbol}'

class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(null=True)
    bar_code = models.CharField(max_length=64, null=True)
    amount = models.IntegerField(default=0)
    unit_price = models.DecimalField(max_digits=11, decimal_places=2, default=0.00)
    unit_type = models.ForeignKey(UnitType, on_delete=models.SET_NULL, null=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, null=True)
    manufacturer_code = models.CharField(max_length=64, null=True)

    def __str__(self):
        return f'{self.bar_code} - {self.name}'

stock/forms.py
from django import forms
from stock.models import Product

class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.field.__class__.__name__ in ['ModelChoiceField']:
                visible.field.widget.attrs['class'] = 'form-select'
            else:
                visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Product
        fields = ["name", "bar_code", "manufacturer", "manufacturer_code", "unit_type", "amount", "unit_price"]
        labels = {
            "bar_code": "Código de barras",
            "name": "Nome",
            "manufacturer": "Fabricante",
            "manufacturer_code": "Código do fabricante",
            "unit_type": "Tipo de unidade",
            "amount": "Quantidade",
            "unit_price": "Preço unitário",
        }

kdr/views.py
from django.shortcuts import render

# Create your views here.

stock/views.py
from django.urls import reverse_lazy
from django.views import generic
from stock.models import Product
from stock.forms import ProductForm

class ProductListView(generic.ListView):
    model = Product
    template_name = "product/list.html"

class ProductDetailView(generic.DetailView):
    model = Product
    template_name = "product/detail.html"

class ProductCreateView(generic.CreateView):
    model = Product
    form_class = ProductForm
    template_name = "product/create.html"
    success_url = reverse_lazy("product-list")

class ProductUpdateView(generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "product/update.html"
    success_url = reverse_lazy("product-list")

class ProductDeleteView(generic.DeleteView):
    model = Product
    template_name = "product/delete.html"
    success_url = reverse_lazy("product-list")

kdr/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/fa/css/all.min.css' %}">
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/base.css' %}">

    {% block head %}
    <title>Page Title</title>
    {% endblock %}
</head>

<body class="d-flex flex-row align-items-stretch min-vh-100" onload="loadCurrentAsideNavbarState()">
    <aside class="collapse-aside-navbar collapse collapse-horizontal" id="aside-navbar">
        <div class="aside-navbar">
            <nav class="navbar d-flex flex-column align-items-stretch py-0">
                <div class="px-3 py-3 text-center">
                    <strong>Kasa dos reparos</strong>
                </div>
    
                <ul class="navbar-nav mt-5">
                    <li class="nav-item">
                        <a class="d-block w-100 px-3 py-3" href="{% url 'home' %}">
                            <span class="d-inline-block me-1" style="width: 25px;">
                                <i class="fa-solid fa-house fa-lg"></i>
                            </span>
                            <span class="text-nowrap">Página Inicial</span>
                        </a>
                    </li>
    
                    <li class="nav-item mt-5">
                        <h6 class="d-block w-100 px-3">Menu</h6>
                    </li>
                    <li class="nav-item">
                        <a class="d-block w-100 px-3 py-3" href="#">
                            <span class="d-inline-block me-1" style="width: 25px;">
                                <i class="fa-solid fa-chart-line fa-lg"></i>
                            </span>
                            <span class="text-nowrap">Dashboards</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="d-block w-100 px-3 py-3" href="{% url 'product-list' %}">
                            <span class="d-inline-block me-1" style="width: 25px;">
                                <i class="fa-solid fa-boxes-stacked fa-lg"></i>
                            </span>
                            <span class="text-nowrap">Produtos</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="d-block w-100 px-3 py-3" href="#">
                            <span class="d-inline-block me-1" style="width: 25px;">
                                <i class="fa-solid fa-circle-dollar-to-slot fa-lg"></i>
                            </span>
                            <span class="text-nowrap">Vendas</span>
                        </a>
                    </li>
                </ul>
    
            </nav>
        </div>
    </aside>

    <section class="w-100">
        <header class="d-flex flex-row justify-content-between">
            <ul class="d-flex flex-row">
                <li>
                    <a class="d-block w-100 px-3 py-3" id="aside-navbar-button" data-bs-toggle="collapse" href=".collapse-aside-navbar" role="button" aria-expanded="false" aria-controls="aside-navbar">
                        <i class="fa-solid fa-bars fa-xl collapse-aside-navbar collapse collapse-horizontal show" id="aside-navbar-button-icon-show"></i>
                        <i class="fa-solid fa-xmark fa-xl collapse-aside-navbar collapse collapse-horizontal" id="aside-navbar-button-icon-hide"></i>
                    </a>
                </li>
            </ul>

            <ul class="d-flex flex-row">
                <li>
                    <a class="d-block w-100 px-3 py-3" href="#">
                        <i class="fa-solid fa-bell fa-xl"></i>
                    </a>
                </li>
                <li>
                    <a class="d-block w-100 px-3 py-3" href="#">
                        <i class="fa-solid fa-cart-shopping fa-xl"></i>
                    </a>
                </li>
                <li>
                    <a class="d-block w-100 px-3 py-3" href="#">
                        <i class="fa-solid fa-gear fa-xl"></i>
                    </a>
                </li>
            </ul>
        </header>

        <main class="px-3 py-3">
            {% block content %}
            {% endblock %}
        </main>
    </section>

    <script src="{% static '/js/kdr.base.js' %}"></script>
</body>

</html>

kdr/templates/components/btn_return.html
<div class="d-flex flex-row justify-content-between align-items-center">
    <h3 style="margin-bottom: 0px;">{{ page_title|default:"Título" }}</h3>
    <a class="btn btn-outline-dark rounded-2 py-2" href={{ return_url|default:"#" }}>
        <span><i class="fa-solid fa-angle-left"></i></span>
        <span class="text-nowrap">{{ return_text|default:"Voltar" }}</span>
    </a>
</div>

kdr/templates/kdr/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>Página inicial</title>
{% endblock %}

{% block content %}
    <h2>Página inicial</h2>
{% endblock %}

stock/templates/product/create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>Novo Produto</title>
{% endblock %}

{% block content %}
    <!-- title -->
    {% url 'product-list' as return_url %}
    {% include 'components/btn_return.html' with page_title='Novo do produto' return_url=return_url %}

    <!-- breadcrumb -->
    <div style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb text-nowrap">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'product-list' %}">Produtos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Novo produto</li>
        </ol>
    </div>

    <!-- main data -->
    <div class="border rounded-2 p-3" style="background-color: var(--neutral50);">
        <form method="post" id="update-product">
            {% csrf_token %}  

            <div class="row g-3">
                <div class="col-lg-3">
                    {{ form.bar_code.errors }}
                    <label for="{{ form.bar_code.id_for_label }}" class="form-label text-nowrap">
                        {{ form.bar_code.label }}{% if form.bar_code.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.bar_code }}
                </div>
                <div class="col-lg-9">
                    {{ form.name.errors }}
                    <label for="{{ form.name.id_for_label }}" class="form-label text-nowrap">
                        {{ form.name.label }}{% if form.name.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.name }}
                </div>

                <div class="col-lg-6">
                    {{ form.manufacturer.errors }}
                    <label for="{{ form.manufacturer.id_for_label }}" class="form-label text-nowrap">
                        {{ form.manufacturer.label }}{% if form.manufacturer.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.manufacturer }}
                </div>
                <div class="col-lg-6">
                    {{ form.manufacturer_code.errors }}
                    <label for="{{ form.manufacturer_code.id_for_label }}" class="form-label text-nowrap">
                        {{ form.manufacturer_code.label }}{% if form.manufacturer_code.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.manufacturer_code }}
                </div>

                <div class="col-lg-4">
                    {{ form.unit_type.errors }}
                    <label for="{{ form.unit_type.id_for_label }}" class="form-label text-nowrap">
                        {{ form.unit_type.label }}{% if form.unit_type.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.unit_type }}
                </div>
                <div class="col-lg-4">
                    {{ form.amount.errors }}
                    <label for="{{ form.amount.id_for_label }}" class="form-label text-nowrap">
                        {{ form.amount.label }}{% if form.amount.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.amount }}
                </div>
                <div class="col-lg-4">
                    {{ form.unit_price.errors }}
                    <label for="{{ form.unit_price.id_for_label }}" class="form-label text-nowrap">
                        {{ form.unit_price.label }}{% if form.unit_price.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.unit_price }}
                </div>
            </div>
        </form>

        <!-- form action buttons -->
        <div class="mt-3">
            <div class="d-flex justify-content-end gap-2">
                <a class="d-block-inline btn btn-secondary rounded-2 py-2" role="button" href="{% url 'product-list' %}">
                    <span>
                        <i class="fa-solid fa-xmark"></i>
                    </span>
                    <span class="text-nowrap">Cancelar</span>
                </a>
                <button type="submit" form="update-product" class="btn btn-success rounded-2 py-2">
                    <span>
                        <i class="fa-solid fa-check"></i>
                    </span>
                    <span class="text-nowrap">Adicionar</span>
                </button>
            </div>
        </div>
    </div>
{% endblock %}

stock/templates/product/delete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>Deletar produto</title>
{% endblock %}

{% block content %}
    <!-- title -->
    {% url 'product-detail' product.id as return_url %}
    {% include 'components/btn_return.html' with page_title='Deletar do produto' return_url=return_url %}

    <!-- breadcrumb -->
    <div style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb text-nowrap">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'product-list' %}">Produtos</a></li>
            <li class="breadcrumb-item"><a href="{% url 'product-detail' object.id %}">{{ object.bar_code }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Deletar</li>
        </ol>
    </div>

    <!-- main data -->
    <div class="border rounded-2 p-3" style="background-color: var(--neutral50);">
        <form method="post" id="delete-product">
            {% csrf_token %} 
            <div class="d-flex justify-content-center">
                <p class="text-nowrap">Tem certeza que deseja deletar esse produto?</p>
            </div>

            <div class="bg-danger-subtle border rounded-2 border-danger p-3">
                <div>
                    <div class="d-flex flex-row justify-content-between border-bottom border-secondary pb-2 mb-2">
                        <label for="id_bar_code" class="text-nowrap">Código de barra</label>
                        <span id="id_bar_code" class="text-nowrap">{{ object.bar_code }}</span>
                    </div>
                    <div class="d-flex flex-row justify-content-between border-bottom border-secondary pb-2 mb-2">
                        <label for="id_name" class="text-nowrap">Nome</label>
                        <span id="id_name" class="text-nowrap">{{ object.name }}</span>
                    </div>
                    <div class="d-flex flex-row justify-content-between border-bottom border-secondary pb-2 mb-2">
                        <label for="id_manufacturer" class="text-nowrap">Fabricante</label>
                        <span id="id_manufacturer" class="text-nowrap">{{ object.manufacturer }}</span>
                    </div>
                    <div class="d-flex flex-row justify-content-between border-bottom border-secondary pb-2 mb-2">
                        <label for="id_manufacturer_code" class="text-nowrap">Código do fabricante</label>
                        <span id="id_manufacturer_code" class="text-nowrap">{{ object.manufacturer_code }}</span>
                    </div>
                    <div class="d-flex flex-row justify-content-between">
                        <label for="id_amount" class="text-nowrap">Quantidade</label>
                        <span id="id_amount" class="text-nowrap">{{ object.amount }} {{ object.unit_type }}</span>
                    </div>
                </div>
            </div>
        </form>

        <!-- form action buttons -->
        <div class="mt-3">
            <div class="d-flex justify-content-end gap-2">
                <a class="d-block-inline btn btn-secondary rounded-2 py-2" role="button" href="{% url 'product-detail' product.id %}">
                    <span>
                        <i class="fa-solid fa-xmark"></i>
                    </span>
                    <span class="text-nowrap">Cancelar</span>
                </a>
                <button type="submit" form="delete-product" class="btn btn-danger rounded-2 py-2">
                    <span>
                        <i class="fa-solid fa-trash-can"></i>
                    </span>
                    <span class="text-nowrap">Deletar</span>
                </button>
            </div>
        </div>
    </div>
{% endblock %}

stock/templates/product/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>Detalhes do produto</title>
{% endblock %}

{% block content %}
    <!-- title -->
    {% url 'product-list' as return_url %}
    {% include 'components/btn_return.html' with page_title='Detalhes do produto' return_url=return_url %}

    <!-- breadcrumb -->
    <div style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb text-nowrap">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'product-list' %}">Produtos</a></li>
            <li class="breadcrumb-item" aria-current="page">{{ object.bar_code }}</li>
        </ol>
    </div>

    <!-- actions button -->
    <div class="py-2">
        <div class="d-flex justify-content-end gap-2">
            <a href="{% url 'product-delete' product.id %}" class="btn btn-danger rounded-2 px-2 py-2">
                <span class="d-inline-block text-center" style="width: 24px;">
                    <i class="fa-solid fa-trash-can"></i>
                </span>
                <span class="text-nowrap">Deletar</span>
            </a>
            <a href="{% url 'product-update' product.id %}" class="btn btn-warning rounded-2 px-2 py-2">
                <span class="d-inline-block text-center" style="width: 24px;">
                    <i class="fa-solid fa-pen-to-square"></i>
                </span>
                <span class="text-nowrap">Atualizar</span>
            </a>
        </div>
    </div>

    <!-- main data -->
    <div class="border rounded-2 p-3" style="background-color: var(--neutral50);">
        <div class="row g-3">
            <div class="col-lg-3">
                <label for="id_bar_code" class="form-label text-nowrap">
                    Código de barras
                </label>
                <input type="text" name="bar_code" value={{ object.bar_code }} class="form-control" id="id_bar_code" readonly>
            </div>
            <div class="col-lg-9">
                
                <label for="id_name" class="form-label text-nowrap">
                    Nome
                </label>
                <input type="text" name="name" value={{ object.name }} class="form-control" id="id_name" readonly>
            </div>

            <div class="col-lg-6">
                <label for="id_manufacturer" class="form-label text-nowrap">
                    Fabricante
                </label>
                <input type="text" name="manufacturer" value={{ object.manufacturer }} class="form-control" id="id_manufacturer" readonly>
            </div>
            <div class="col-lg-6">
                <label for="id_manufacturer_code" class="form-label text-nowrap">
                    Código do fabricante
                </label>
                <input type="text" name="manufacturer_code" value={{ object.manufacturer_code }} class="form-control" id="id_manufacturer_code" readonly>
            </div>

            <div class="col-lg-4">
                <label for="id_unit_type" class="form-label text-nowrap">
                    Tipo de unidade
                </label>
                <input type="text" name="unit_type" value={{ object.unit_type }} class="form-control" id="id_unit_type" readonly>
            </div>
            <div class="col-lg-4">
                <label for="id_amount" class="form-label text-nowrap">
                    Quantidade
                </label>
                <input type="number" name="amount" value={{ object.amount }} class="form-control" id="id_amount" readonly>
            </div>
            <div class="col-lg-4">
                <label for="id_unit_price" class="form-label text-nowrap">
                    Preço unitário
                </label>
                <input type="number" name="unit_price" value="1.00" class="form-control" id="id_unit_price" readonly>
            </div>
        </div>
    </div>
{% endblock %}

stock/templates/product/list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static '/css/list.css' %}">
    <title>Lista de produtos</title>
{% endblock %}

{% block content %}
    <!-- title -->
    {% url 'home' as return_url %}
    {% include 'components/btn_return.html' with page_title='Produtos' return_url=return_url %}
    
    <!-- breadcrumb -->
    <div style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Produtos</li>
        </ol>
    </div>

    <!-- actions button -->
    <div class="py-2">
        <div class="d-flex justify-content-end">
            <a class="btn btn-success rounded-2 py-2" href="{% url 'product-create' %}">
                <span>
                    <i class="fa-solid fa-plus"></i>
                </span>
                <span class="text-nowrap">Novo produto</span>
            </a>
        </div>
    </div>

    <!-- main data -->
    <div class="border rounded-2 p-3" style="background-color: var(--neutral50);">
        <div class="d-none d-lg-flex text-center rounded-2 kdr-table-header">
            <span class="d-inline-block px-2 py-2" style="min-width: 120px;">Cd. Barra</span>
            <span class="d-inline-block flex-grow-1 px-2 py-2">Produto</span>
            <span class="d-inline-block px-2 py-2" style="min-width: 140px;">Quantidade</span>
            <span class="d-inline-block px-2 py-2" style="min-width: 220px;">Preço Unitário</span>
            <span class="d-inline-block px-2 py-2" style="min-width: 40px;"></span>
        </div>
    
        <div class="d-flex flex-column">
            {% for product in object_list %}
                <a class="kdr-table-item-slot" href="{% url 'product-detail' product.id %}">
                        <div class="d-flex flex-row kdr-table-lg-striped hover-item py-1">
                            <div class="d-flex flex-column flex-wrap flex-lg-row flex-lg-nowrap  flex-grow-1">
                                <div class="d-flex flex-row flex-nowrap flex-grow-1">
                                    <span class="d-inline-block px-2 py-2" style="min-width: 120px;">{{ product.bar_code }}</span>
                                    <span class="d-inline-block flex-grow-1 px-2 py-2" style=" min-width: 132px;">{{ product.name }}</span>
                                </div>
                                <div class="d-flex flex-row flex-nowrap flex-grow-1 flex-lg-grow-0 justify-content-between">
                                    <span class="d-inline-block text-lg-center px-2 py-2" style="min-width: 140px;">
                                        {{ product.amount }}
                                        {% if product.unit_type %}{{ product.unit_type|default:"" }}{% endif %}
                                    </span>
                                    <span class="d-inline-block text-end text-lg-center px-2 py-2" style="min-width: 220px;">
                                        R$ {{ product.unit_price }}
                                    </span>
                                </div>
                            </div>
                            <div class="px-2">
                                <span class="d-inline-block text-center p-2" style="width: 24px;">
                                    <i class="fa-solid fa-angle-right"></i>
                                </span>
                            </div>
                        </div>
                </a>
            {% empty %}
                <div>
                     Não há produtos cadastrados.
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

stock/templates/product/update.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>Editar Produto</title>
{% endblock %}

{% block content %}
    <!-- title -->
    {% url 'product-detail' product.id as return_url %}
    {% include 'components/btn_return.html' with page_title='Editar Produto' return_url=return_url %}

    <!-- breadcrumb -->
    <div style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb text-nowrap">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'product-list' %}">Produtos</a></li>
            <li class="breadcrumb-item"><a href="{% url 'product-detail' object.id %}">{{ object.bar_code }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar</li>
        </ol>
    </div>

    <!-- main data -->
    <div class="border rounded-2 p-3" style="background-color: var(--neutral50);">
        <form method="post" id="update-product">
            {% csrf_token %}  

            <div class="row g-3">
                <div class="col-lg-3">
                    {{ form.bar_code.errors }}
                    <label for="{{ form.bar_code.id_for_label }}" class="form-label text-nowrap">
                        {{ form.bar_code.label }}{% if form.bar_code.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.bar_code }}
                </div>
                <div class="col-lg-9">
                    {{ form.name.errors }}
                    <label for="{{ form.name.id_for_label }}" class="form-label text-nowrap">
                        {{ form.name.label }}{% if form.name.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.name }}
                </div>

                <div class="col-lg-6">
                    {{ form.manufacturer.errors }}
                    <label for="{{ form.manufacturer.id_for_label }}" class="form-label text-nowrap">
                        {{ form.manufacturer.label }}{% if form.manufacturer.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.manufacturer }}
                </div>
                <div class="col-lg-6">
                    {{ form.manufacturer_code.errors }}
                    <label for="{{ form.manufacturer_code.id_for_label }}" class="form-label text-nowrap">
                        {{ form.manufacturer_code.label }}{% if form.manufacturer_code.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.manufacturer_code }}
                </div>

                <div class="col-lg-4">
                    {{ form.unit_type.errors }}
                    <label for="{{ form.unit_type.id_for_label }}" class="form-label text-nowrap">
                        {{ form.unit_type.label }}{% if form.unit_type.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.unit_type }}
                </div>
                <div class="col-lg-4">
                    {{ form.amount.errors }}
                    <label for="{{ form.amount.id_for_label }}" class="form-label text-nowrap">
                        {{ form.amount.label }}{% if form.amount.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.amount }}
                </div>
                <div class="col-lg-4">
                    {{ form.unit_price.errors }}
                    <label for="{{ form.unit_price.id_for_label }}" class="form-label text-nowrap">
                        {{ form.unit_price.label }}{% if form.unit_price.field.required %}<span class="field-required">*</span>{% endif %}
                    </label>
                    {{ form.unit_price }}
                </div>
            </div>
        </form>

        <!-- form action buttons -->
        <div class="mt-3">
            <div class="d-flex justify-content-end gap-2">
                <a class="d-block-inline btn btn-secondary rounded-2 py-2" role="button" href="{% url 'product-detail' product.id %}">
                    <span>
                        <i class="fa-solid fa-xmark"></i>
                    </span>
                    <span class="text-nowrap">Cancelar</span>
                </a>
                <button type="submit" form="update-product" class="btn btn-warning rounded-2 py-2">
                    <span>
                        <i class="fa-solid fa-check"></i>
                    </span>
                    <span class="text-nowrap">Atualizar</span>
                </button>
            </div>
        </div>
    </div>
{% endblock %}